gsb_report_accueil:
    path:     /
    defaults: { _controller: GSBReportBundle:Rapport:index }

gsb_report_medicaments:
    path:     /medicaments/
    defaults: { _controller: GSBReportBundle:Medicament:afficher }
    
gsb_report_medicaments_rechercher:
    path:     /medicaments/rechercher/
    defaults: { _controller: GSBReportBundle:Medicament:rechercher }
    
gsb_report_medicaments_famille:
    path:     /medicaments/famille/{id}
    defaults: { _controller: GSBReportBundle:Medicament:afficherFamille }
    requirements:
        _method:  GET
        id: \d+
    
gsb_report_praticiens:
    path:     /praticiens/
    defaults: { _controller: GSBReportBundle:Praticien:afficher }

gsb_report_praticiens_rechercher:
    path:     /praticiens/rechercher/
    defaults: { _controller: GSBReportBundle:Praticien:rechercher }

gsb_report_praticiens_type:
    path:     /praticiens/type/{id}
    defaults: { _controller: GSBReportBundle:Praticien:afficherType }
    requirements:
        _method:  GET
        id: \d+

gsb_report_praticiens_avance:
    path:     /praticiens/nom/{nom}/ville/{ville}
    defaults: { _controller: GSBReportBundle:Praticien:afficherAvance, nom: "all", ville: "all" }
    requirements:
        _method:  GET
    
gsb_report_rapports:
    path:     /rapports/
    defaults: { _controller: GSBReportBundle:Rapport:afficher }

gsb_report_rapports_add:
    path:     /rapports/ajouter/
    defaults: { _controller: GSBReportBundle:Rapport:ajouter }