services:
    user.form.profile.type:
        class: GSB\UserBundle\Form\Type\ProfileFormType
        parent: fos_user.profile.form.type
        tags:
            - { name: form.type, alias: gsb_user_profile }
