<?php

namespace GSB\ReportBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MedicamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicamentRepository extends EntityRepository {

    public function getMedicamentsByFamille($id) {
        $qb = $this->createQueryBuilder('m')
                ->select('m')
                ->join('m.famille', 'f', 'WITH', 'f.id = :id')
                ->setParameter('id', $id)
                ->addSelect('f');
        return $qb->getQuery()->getResult();
    }

}
