<?php

namespace GSB\ReportBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MedicamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicamentRepository extends EntityRepository
{
    
    /**
     * Retourner tous les médicaments.
     * 
     * @return tous les médicaments
     */
    public function getMedicaments()
    {
        $qb = $this->createQueryBuilder('m')
                   ->select('m')
                   ->join('m.famille', 'f')
                   ->addSelect('f');
        
        return $qb->getQuery()->getResult();
    }
    
    /**
     * Retourner tous les médicaments d'une famille donnée en paramètre.
     * 
     * @param int $id l'id de la famille
     * @return les médicaments d'une famille
     */
    public function getMedicamentsByFamille($id)
    {
        $qb = $this->createQueryBuilder('m')
                   ->select('m')
                   ->join('m.famille', 'f', 'WITH', 'f.id = :id')
                   ->setParameter('id', $id)
                   ->addSelect('f');
        
        return $qb->getQuery()->getResult();
    }

}
