<?php

namespace GSB\ReportBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PracticienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PraticienRepository extends EntityRepository {

    public function getPraticiensByType($id) {
        $qb = $this->createQueryBuilder('p')
                ->select('p')
                ->join('p.typepraticien', 't', 'WITH', 't.id = :id')
                ->setParameter('id', $id)
                ->addSelect('t');
        return $qb->getQuery()->getResult();
    }

}
