<?php

namespace GSB\ReportBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PracticienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PraticienRepository extends EntityRepository {

    public function getPraticiensByType($id) {
        $qb = $this->createQueryBuilder('p')
                ->select('p')
                ->join('p.typepraticien', 't', 'WITH', 't.id = :id')
                ->setParameter('id', $id)
                ->addSelect('t');
        return $qb->getQuery()->getResult();
    }
    
    public function getPraticiensByAvance($nom, $ville) {
        if ($nom === "all" && $ville === "all") {
            $qb = $this->createQueryBuilder('p')
                ->select('p');
        } else if ($nom !== "all") {
            $qb = $this->createQueryBuilder('p')
                ->select('p')
                ->where('p.nomMedecin LIKE :nom')
                ->setParameter('nom', '%'.$nom.'%');
        } else if (!$ville !== "all") {
            $qb = $this->createQueryBuilder('p')
                ->select('p')
                ->where('p.villeMedecin LIKE :ville')
                ->setParameter('ville', '%'.$ville.'%');
        } else {
            $qb = $this->createQueryBuilder('p')
                ->select('p')
                ->andWhere('p.nomMedecin LIKE :nom')
                ->setParameter('nom', '%'.$nom.'%')
                ->where('p.villeMedecin LIKE :ville')
                ->setParameter('ville', '%'.$nom.'%');
        }
        
        return $qb->getQuery()->getResult();
    }

}
