<?php

namespace GSB\ReportBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RapportvisiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RapportvisiteRepository extends EntityRepository
{
    
    /**
     * Retourner tous les rapports.
     * 
     * @return tous les rapports
     */
    public function getRapports()
    {
        $qb = $this->createQueryBuilder('r')
                   ->select('r')
                   ->join('r.medecin', 'm')
                   ->addSelect('m');
        
        return $qb->getQuery()->getResult();
    }
}