<?php

namespace GSB\ReportBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypepraticienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypepraticienRepository extends EntityRepository
{
    
}